services:
  postgres:
    image: postgres:15
    container_name: delivery-app-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: delivery-app
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  nest:
    build: .
    container_name: delivery-app-api
    depends_on:
      - postgres
    ports:
      - '4001:4001'
    env_file:
      - .env.docker
volumes:
  pgdata:
