services:
  postgres:
    image: postgres:15
    container_name: delivery-app-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: delivery-app
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  nest:
    build: .
    container_name: delivery-app-api
    depends_on:
      - postgres
    ports:
      - '4001:4000'
    # env_file:
    #   - .env
    environment: 
      - DATABASE_URL=postgresql://postgres:123456@delivery-app-db:5432/delivery-app
    #   - DATABASE_URL: postgresql://postgres:123456@localhost:5432/delivery-app

volumes:
  pgdata:
